name: Test Flaky

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'
      - name: Maven
        run: mvn clean install -Drat.skip -Dskiptests -Dcheckstyle.skip -Dmaven.test.skip=true

      - name: Compile the project
        run: mvn test-compile -pl riptide-spring-boot-starter -am -Drat.skip -Dskiptests -Dcheckstyle.skip -e -X
  
      - name: Run tests
        run: mvn -pl riptide-spring-boot-starter test -Dtest=org.zalando.riptide.spring.AccessTokensDefaultCredentialsDirectoryTest#shouldUseCredentialsDirectory -e -X
        
      # - name: Set up JDK 8 for NonDex
      #   uses: actions/setup-java@v2
      #   with:
      #     distribution: 'adopt'
      #     java-version: '8'
  
      - name: Run NonDex to check for flaky tests
        run: mvn -pl riptide-spring-boot-starter edu.illinois:nondex-maven-plugin:2.1.7:nondex -Dtest=org.zalando.riptide.spring.AccessTokensDefaultCredentialsDirectoryTest#shouldUseCredentialsDirectory -DnondexRuns=20
